config/routes.rb
Refinery::Core::Engine.routes.draw do
  get 'blog/most_popular', to: "blog/posts#most_popular"
  get "signup", to: "pages#signup", as: :signup_page
end

Rails.application.routes.draw do
  resources :orders, only: [:edit, :update]
  get 'pricing', to: 'orders#edit', as: :pricing_page
  patch 'agree_to_terms', to: 'orders#agree_to_terms', as: :agree_to_terms
  patch 'reset_order', to: 'orders#reset_order', as: :reset_order
  get 'completed_order/*order_id', to: 'orders#completed_order', as: :completed_order
  post 'lead_capture', to: 'orders#lead_capture', as: :lead_capture

  resources :order_items, only: [:edit, :create, :update]

  resources :brief_requests, only: [:update]

  resources :charges, only: [:new, :create] do
    get :bitpay, on: :collection
    get :bitpay_callback, on: :collection
  end

  get 'checkout', to: 'charges#new', as: :checkout_page

  get 'media', to: 'static_pages#media', as: :media_page
  get 'about-us', to: 'static_pages#about_us', as: :about_us
  get 'service-agreement', to: 'static_pages#service_agreement', as: :service_agreement_page
  get 'podcast', to: 'static_pages#podcast', as: :podcast_page
  get 'mailchimp_list', to: 'static_pages#mailchimp_list', as: :mailchimp_list
  get 'callrequest', to: 'static_pages#callrequest', as: :callrequest

  post 'contact/submit', to: 'contact_form#submit'

  get '/podcasts.rss', to: redirect('https://feeds.simplecast.com/iKb8D4_d', status: 301)

  # https://feeds.simplecast.com/iKb8D4_d
  # This line mounts Refinery's routes at the root of your application.
  # This means, any requests to the root URL of your application will go to Refinery::PagesController#home.
  # If you would like to change where this extension is mounted, simply change the
  # configuration option `mounted_path` to something different in config/initializers/refinery/core.rb
  #
  # We ask that you don't use the :as option here, as Refinery relies on it being the default of "refinery"

  match '*path', via: :all, to: 'errors#not_found', constraints: CloudfrontConstraint.new

  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path
  # require 'sidekiq/web'
  # authenticate :user, lambda { |u| u.is_admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def media
    # Neuralle account
    @instagram = InstagramApi.user(8022410616).recent_media({count: 4}).data

    # Tony test account
    # @instagram = InstagramApi.user(8503516048).recent_media({count: 4}).data
  end

  def about_us
  end

  def service_agreement
  end

  def podcast
    @podcasts = Refinery::Podcasts::Podcast.order('published_at DESC')
  end

  def mailchimp_list
    gibbon = Gibbon::Request.new(api_key: ENV['MAILCHIMP_API_KEY'])
    gibbon.timeout = 30
    gibbon.open_timeout = 30

    lists = gibbon.lists.retrieve
    data = lists["lists"].map do |item|
      { id: item["id"],
        web_id: ["web_id"],
        name: item["name"],
        subscribe_url_long: item["subscribe_url_long"]
      }
    end

    render json: data
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

  def about_companies_logos
    ["development_ready_logo.png", "go_markets_logo.png", "uncommon_logo.png", "infinity_logo.png", "coinjar_logo.svg", "bgs_logo.png", "lwc_logo.png"]
  end

  def image_id(image)
    image[0...-4].gsub("_", "-")
  end

end

app/views/static_pages/_roles.html.haml
#portraits
  .role
    = image_tag "about_us/jordan.jpg"
    %p Jordan is Managing&nbsp;Director and is&nbsp;in&nbsp;charge of&nbsp;all&nbsp;things&nbsp;strategy, sales and&nbsp;marketing.
  .role
    = image_tag "about_us/lauren.jpg"
    %p Lauren is Creative&nbsp;Director and&nbsp;takes&nbsp;care of&nbsp;everything related&nbsp;to&nbsp;production, creative and&nbsp;studio.

app/views/static_pages/about_us.html.haml
#about-us
  .masthead
    %h1 About Us

  %section#brief
    .container

      .image
        .vertical-align
          = image_tag "about_us/lauren_jordan.jpg"
      .text
        %p Hello, we're Jordan&nbsp;Michaelides and Lauren&nbsp;Lopatko, co-founders of&nbsp;Neuralle and&nbsp;partners&nbsp;in&nbsp;life.
        %p We are “High&nbsp;School&nbsp;sweethearts” who bonded immediately over a&nbsp;passion for&nbsp;design, persuasion, new&nbsp;ideas and&nbsp;unique&nbsp;experiences. We&nbsp;stand here&nbsp;today, 10&nbsp;years&nbsp;later, as&nbsp;partners in&nbsp;crime with a&nbsp;media&nbsp;business that&nbsp;utilises the&nbsp;best of&nbsp;both&nbsp;of&nbsp;us – for&nbsp;you.
        %p Originally formed as a podcast, Neuralle has grown into a specialised content production business that focuses on audio & video production.
        %p When one of our very first clients reached out for help to create and distribute their own podcast, the idea for Neuralle Media and the business was born.
      .clearfix

  %section#roles
    .container
      = render "roles"

app/views/static_pages/callrequest.html.haml
#callrequest
  .modal.static#lead-capture-modal{ :role => "dialog" }
    = render "orders/lead_capture_modal"

app/views/static_pages/media.html.haml
- title_tag "Podcast & Video Production, Automated | Neuralle"
- description_tag "Neuralle Media is Affordable and Effortless Content Production"

#media
  .masthead
    .dimming
    .container
      .text
        %h1 We grow customers, through&nbsp;content
        %h2 Neuralle specialises in audio & video content that&nbsp;generates&nbsp;growth.
        .btn-wrapper
          = link_to 'Check out Pricing', pricing_page_path, class: 'btn bold cta green'
          %span or
          = link_to 'Talk to a Strategist', callrequest_path, class: 'btn bold cta green'
      .clearfix

  %section#apps-list
    .container
      %h2 A customisable selection of content options
      %h4 Built for companies, by media practitioners
      = render "static_pages/media/apps"

  %section#what
    .container
      %h1 So how does it work?
      = render "static_pages/media/what_carousel"

  - if @instagram.present?
    %section#instagram-carousel
      .container
        .narrow
          %h2 Check out our feed
          = render "static_pages/media/instagram_media_carousel"

  %section#who
    .container
      %h2 Neuralle is for...
      %p Business owners, content teams, and freelancers of all shapes and sizes. Our service's flexibility helps you deliver unique and engaging content with an offering that is both affordable and effortless.
      = link_to "Common Questions", "javascript:void(0)", class: "btn cta", id: "faq-toggle"
      #faq
        %h2 Common Questions
        %h4 What is Neuralle Media?
        %p Neuralle media is a quick, easy to use, content media and distribution service. Similar to an eCommerce or SaaS system we’ve built our infrastructure so you can quickly price up an option and have the ultimate solution confirmed in 15-20 minutes.

        %h4 How do I use Neuralle Media?
        %p Simply choose your preferred monthly or one-off option. Then select how much content you’d like produced, distributed or how many social channels managed at
        = link_to 'on our Pricing page.', pricing_page_path

        %h4 What methods can I pay with?
        %p We offer payment in Mastercard, VISA, AMEX, Bitcoin and Bitcoin Cash.

        %h4 What happens after payment?
        %p Our team will get to work on transforming your brief into a digestible piece of work for our freelancers, providing you with an ETA on delivery via email.
        %p For monthly bundle clients, we will set up your private Slack Channel & Google Drives, making contact within 24 hours.

  %section#why
    .container
      = render "static_pages/media/media_carousel"

  %section#work-with.logos-list
    %h2 Who we've worked with
    .container
      .logos
        - about_companies_logos.each do |company_logo|
          .outer
            = image_tag "media/#{company_logo}", id: "#{image_id(company_logo)}"
        -# .clearfix

      -# .logos
        = link_to "https://www.developmentready.com.au/", target: "_blank" do
          = image_tag "media/development_ready_logo.png"
        = link_to podcast_page_path, target: "_blank" do
          = image_tag "media/uncommon_logo.png"
        = link_to "https://www.gomarkets.com.au/", target: "_blank" do
          = image_tag "media/go_markets_logo.png"
        = link_to "https://www.infinitywellnesscentre.com.au/", target: "_blank" do
          = image_tag "media/infinity_logo.png"
        = link_to "https://www.infinitywellnesscentre.com.au/", target: "_blank" do
          = image_tag "media/coinjar_logo.svg"

      -# #companies-list

  %section.subscribtion-form
    .container
      .row
        .col-sm-6.image
          = image_tag "headphones.jpg"
        .col-md-5.col-sm-6#mc_embed_signup
          %h4 Learn How to Create Podcasts & Video, to help grow your business.
          = render "shared/mailchimp_form", action: "https://neuralle.us10.list-manage.com/subscribe/post?u=c7a21948a398f006f046c5731&amp;id=f6f3bca6ff", key: "b_c7a21948a398f006f046c5731_f6f3bca6f"
        .clearfix

  %section#about-us
    .container
      .centered-text
        %h2 About Us
        %p Hello, we're Jordan&nbsp;Michaelides and Lauren&nbsp;Lopatko, co-founders of&nbsp;Neuralle and&nbsp;partners&nbsp;in&nbsp;life.
        %p We are “High&nbsp;School&nbsp;sweethearts” who bonded immediately over a&nbsp;passion for&nbsp;design, persuasion, new&nbsp;ideas and&nbsp;unique&nbsp;experiences. We&nbsp;stand here&nbsp;today, 10&nbsp;years&nbsp;later, as&nbsp;partners in&nbsp;crime with a&nbsp;media&nbsp;business that&nbsp;utilises the&nbsp;best of&nbsp;both&nbsp;of&nbsp;us – for&nbsp;you.
      = render "roles"




  -# %section#testimonials
    .container
      = render "static_pages/media/testimonials"

app/views/static_pages/podcast.html.haml
- title_tag "Listen to Uncommon | Neuralle"
- description_tag "Listening to the Uncommon podcast allows you to learn the knowledge, processes, and mindset of unique individuals."

.container
  #body_content
    %link{:href => "//cdn-images.mailchimp.com/embedcode/classic-10_7.css", :rel => "stylesheet", :type => "text/css"}/
    .row
      .col-md-12
        #mc_embed_signup
          %form#mc-embedded-subscribe-form.validate{:action => "//neuralle.us10.list-manage.com/subscribe/post?u=c7a21948a398f006f046c5731&id=5cff14c3b7", :method => "post", :name => "mc-embedded-subscribe-form", :novalidate => "", :target => "_blank"}
            #mc_embed_signup_scroll
              = render "static_pages/podcast/podcast_content", podcasts: @podcasts
              .subscribe-form
                .indicates-required
                  %span.asterisk *
                  indicates required
                .mc-field-group
                  %label{:for => "mce-EMAIL"}
                    Email Address
                    %span.asterisk *
                  %input#mce-EMAIL.required.email{:name => "EMAIL", :type => "email", :value => ""}/
                .mc-field-group
                  %label{:for => "mce-FNAME"}
                    First Name
                    %span.asterisk *
                  %input#mce-FNAME.required{:name => "FNAME", :type => "text", :value => ""}/
                .mc-field-group
                  %label{:for => "mce-LNAME"} Last Name
                  %input#mce-LNAME{:name => "LNAME", :type => "text", :value => ""}/
                #mce-responses.clear
                  #mce-error-response.response
                  #mce-success-response.response
                %div.subscribe-form-aria
                  %input{:name => "b_c7a21948a398f006f046c5731_5cff14c3b7", :tabindex => "-1", :type => "text", :value => ""}/
                .clear
                  %input#mc-embedded-subscribe.btn.primary.bold{:name => "subscribe", :type => "submit", :value => "Subscribe"}/

app/views/static_pages/service_agreement.html.haml
#agreement
  .container
    = render 'service_agreement_doc'