config/routes.rb
Refinery::Core::Engine.routes.draw do
  get 'blog/most_popular', to: "blog/posts#most_popular"
  get "signup", to: "pages#signup", as: :signup_page
end

Rails.application.routes.draw do
  resources :orders, only: [:edit, :update]
  get 'pricing', to: 'orders#edit', as: :pricing_page
  patch 'agree_to_terms', to: 'orders#agree_to_terms', as: :agree_to_terms
  patch 'reset_order', to: 'orders#reset_order', as: :reset_order
  get 'completed_order/*order_id', to: 'orders#completed_order', as: :completed_order
  post 'lead_capture', to: 'orders#lead_capture', as: :lead_capture

  resources :order_items, only: [:edit, :create, :update]

  resources :brief_requests, only: [:update]

  resources :charges, only: [:new, :create] do
    get :bitpay, on: :collection
    get :bitpay_callback, on: :collection
  end

  get 'checkout', to: 'charges#new', as: :checkout_page

  get 'media', to: 'static_pages#media', as: :media_page
  get 'about-us', to: 'static_pages#about_us', as: :about_us
  get 'service-agreement', to: 'static_pages#service_agreement', as: :service_agreement_page
  get 'podcast', to: 'static_pages#podcast', as: :podcast_page
  get 'mailchimp_list', to: 'static_pages#mailchimp_list', as: :mailchimp_list
  get 'callrequest', to: 'static_pages#callrequest', as: :callrequest

  post 'contact/submit', to: 'contact_form#submit'

  get '/podcasts.rss', to: redirect('https://feeds.simplecast.com/iKb8D4_d', status: 301)

  # https://feeds.simplecast.com/iKb8D4_d
  # This line mounts Refinery's routes at the root of your application.
  # This means, any requests to the root URL of your application will go to Refinery::PagesController#home.
  # If you would like to change where this extension is mounted, simply change the
  # configuration option `mounted_path` to something different in config/initializers/refinery/core.rb
  #
  # We ask that you don't use the :as option here, as Refinery relies on it being the default of "refinery"

  match '*path', via: :all, to: 'errors#not_found', constraints: CloudfrontConstraint.new

  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path
  # require 'sidekiq/web'
  # authenticate :user, lambda { |u| u.is_admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end
end

app/controllers/charges_controller.rb
require 'bitpay_sdk'

class ChargesController < ApplicationController
  before_action :set_order
  before_action :set_bitpay_service, only: [:bitpay]

  def new
  end

  def create
    amount = (@order.total_price * 100).to_i
    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    if @order.subscription_type == 1
      create_one_time_payment(amount, customer)
    else
      create_subscription(amount, customer)
    end

    @order.pay

    cookies.delete :latest_tab

    # TODO: Implement email exceptions catcher and notifier
    OrderMailer.order_purchase(@order).deliver_later rescue redirect_to completed_order_path(@order)
    OrderMailer.send_receipt(@order).deliver_later rescue redirect_to completed_order_path(@order)

    redirect_to completed_order_path(@order)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def create_one_time_payment(amount, customer)
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: amount,
      description: 'Neuralle Media Services One Time Payment',
      currency: 'aud'
    )
  end

  def create_subscription(amount, customer)
    product = Stripe::Product.create({
      name: "Neuralle Media Services",
      type: "service"
    })

    plan = Stripe::Plan.create({
      currency: 'aud',
      interval: 'month',
      product: product.id,
      nickname: 'Monthly Subscription',
      amount: 1
    })

    subscription = Stripe::Subscription.create({
      customer: customer.id,
      items: [{
        plan: plan.id,
        quantity: amount
      }]
    })
  end

  def bitpay
    if @order.subscription_type == 1
      token = SecureRandom.urlsafe_base64
      invoice = @service.create_invoice(@order, bitpay_callback_charges_url(token: token))
      session[:bitpay_token] = token

      redirect_to invoice['url']
    else
      redirect_to new_charge_path
    end
  rescue StandardError => ex
    flash[:error] = ex.message
    redirect_to new_charge_path
  end

  def bitpay_callback
    if params[:token] == session[:bitpay_token]
      @order.pay

      OrderMailer.order_purchase(@order).deliver_later rescue redirect_to completed_order_path(@order)

      redirect_to completed_order_path(@order)
    end
  end

  private

  def set_order
    @order = current_order
    # @brief_request = @order.brief_request
  end

  def set_bitpay_service
    @service = BitpayService.new
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
  def payment_description
    @order.subscription_type == 1 ? "One Time Payment" : "Monthly Subscription"
  end
end

app/views/charges/_brief_request.html.haml
= form_for @brief_request, remote: true do |f|
  .row
    .col-sm-6
      = f.text_field :name, class: 'form-control', placeholder: 'Name *'
    .col-sm-6
      = f.text_field :company, class: 'form-control', placeholder: 'Company'

  .row
    .col-sm-6
      = f.email_field :email, class: 'form-control', placeholder: 'Email *'
    .col-sm-6
      = f.phone_field :phone_number, class: 'form-control', placeholder: 'Phone number *'

  .row
    .col-sm-6
      = f.country_select :country, { include_blank: 'Country *' }, { class: 'form-control' }
    .col-sm-6
      = f.text_field :industry, class: 'form-control', placeholder: 'Industry'

  .row
    .col-sm-12
      = f.text_area :brief_description, class: 'form-control', rows: 4, placeholder: "Describe your organisation and target audience, to help us understand your goals. *"
    .col-sm-12
      = f.text_area :design_style, class: 'form-control', rows: 4, placeholder: "Describe the design style you're looking for. For audio content, please make references to your favourite style of audio podcasts. For visual and video design, make sure to reference your favourite video styles with examples - include references to colour and style attributes. *"
    .col-sm-12
      = f.text_area :further_notes, class: 'form-control', rows: 4, placeholder: "Any further notes or concerns we should be aware of?"

  .row
    .col-sm-12
      = f.label :brief_file, "Upload sample material"
      = f.file_field :brief_file

app/views/charges/_payment_details.html.haml
= form_tag charges_path do
  - if flash[:error].present?
    #error-explanation
      %p= flash[:error]

  %script.stripe-button{"data-amount" => @order.total_price * 100, "data-description" => payment_description, "data-key" => Rails.configuration.stripe[:publishable_key], "data-locale" => "auto", "data-email" => @order.email, "data-image" => "/logo_red.png", "data-name" => "Neuralle Pty Ltd", "data-panel-label" => "Pay A{{amount}}", :src => "https://checkout.stripe.com/checkout.js"}

  - if @order.subscription_type == 1
    = link_to bitpay_charges_path, class: 'btn btn-pay-bitcoin' do
      Pay with&nbsp;
      = image_tag 'bitcoin.png'
      = image_tag 'btc-green.png'

app/views/charges/new.html.haml
#checkout
  %section#back
    .container

      .narrow
        = link_to "/pricing", id: "wizard-prev" do
          = image_tag 'checkout/amend.svg'
          Amend my package

        -# #bar.progress
        -#   .progress-bar{ role: "progressbar", "aria-valuenow" => "0", "aria-valuemin" => "100", "aria-valuemax" => "100", style: "width: 0;" }
        -# .clearfix

  %section#review
    .container

      %h2 Your Details
      .customer-info
        .details
          %p= @order.name
          %p= @order.email
          %p= @order.company if @order.company
          %p= @order.phone_number
          %p= country_name(@order.country)
        .specifics
          %p You are: <span>#{order_specifics_business}</span>
          %p Your goal: <span>#{order_specifics_goal}</span>
          %p Regularity: <span>#{order_specifics_regularity}</span>
          %p Do you have a style guide? <span>#{order_specifics_style}</span>
        .clearfix

        - if additional_services?
          .additional-services
            .delimiter
            %h4 Additional Services
            %p.small We’ll contact you with options for host or videographer directly.
            - if podcast_host_present?
              %p Podcast host budget: <b>A$#{ podcast_host_order_item.footage_per_hour } / hour</b>
            - if videographer_hire_order_item.duration > 0
              %p Video footage duration: <b>#{ videographer_hire_order_item.duration } hours</b>
              %p Video footage budget: <b>A$#{ videographer_hire_order_item.footage_per_hour } / hour</b>
        .clearfix

      %h2 Your Package
      #review-list
        = render "orders/review_list"

  %section#payment-details
    = render "charges/payment_details"